import React, { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Search } from 'lucide-react';
import { fakeNewsApi } from '../../api/fakeNewsApi';
import { FakeNewsPrediction } from '../../types';

export default function PredictionHistory() {
  const [search, setSearch] = useState('');

  const { data: fnPredictions, isLoading } = useQuery<FakeNewsPrediction[]>({
    queryKey: ['fakeNewsPredictions'],
    queryFn: () => fakeNewsApi.getPredictions(50),
  });

  const formatted = (fnPredictions || []).map((f: FakeNewsPrediction) => ({
    id: f.id || f.prediction_id,
    model: f.model_name || f.model,
    output: f.prediction_label || f.prediction,
    confidence: `Confidence: ${((f.confidence || 0) * 100).toFixed(1)}%`,
    created_at: f.created_at,
  })).sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime());

  const filtered = formatted.filter((item) => {
    if (search && !item.model?.toLowerCase().includes(search.toLowerCase()) && !item.output?.toLowerCase().includes(search.toLowerCase())) {
      return false;
    }
    return true;
  });

  return (
    <div className="max-w-6xl mx-auto space-y-8">
      <div>
        <h1 className="text-2xl font-bold text-white">Fake News Classification History</h1>
        <p className="text-slate-400 text-sm">
          Audit log of all classification runs generated by trained Fake News NLP models.
        </p>
      </div>

      <div className="bg-slate-900 border border-slate-800 rounded-xl p-4 flex flex-col sm:flex-row items-center justify-between gap-4">
        <div className="relative w-full sm:w-64">
          <Search className="w-3.5 h-3.5 text-slate-500 absolute left-3 top-3" />
          <input
            type="text"
            placeholder="Search by model or output..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full bg-slate-800 border border-slate-700 rounded-lg pl-9 pr-3 py-1.5 text-xs text-white"
          />
        </div>
      </div>

      <div className="bg-slate-900 border border-slate-800 rounded-xl overflow-hidden">
        {isLoading ? (
          <div className="p-8 text-center text-xs text-slate-400">Loading classification history from database...</div>
        ) : !filtered.length ? (
          <div className="p-8 text-center text-xs text-slate-500">
            No classification records found. Test Fake News modules to generate audit logs.
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-xs text-left">
              <thead className="bg-slate-800/50 text-slate-400 uppercase tracking-wider">
                <tr>
                  <th className="px-6 py-3 font-semibold">Date & Time</th>
                  <th className="px-6 py-3 font-semibold">Model Used</th>
                  <th className="px-6 py-3 font-semibold">Classification Result</th>
                  <th className="px-6 py-3 font-semibold">Metric Details</th>
                  <th className="px-6 py-3 font-semibold">Audit ID</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800 text-slate-300">
                {filtered.map((item) => (
                  <tr key={item.id} className="hover:bg-slate-800/30">
                    <td className="px-6 py-3 text-slate-400 whitespace-nowrap">
                      {new Date(item.created_at).toLocaleString()}
                    </td>
                    <td className="px-6 py-3 font-medium text-white">{item.model}</td>
                    <td className="px-6 py-3 font-bold">
                      <span className={item.output === 'REAL' ? 'text-emerald-400' : 'text-rose-400'}>
                        {item.output}
                      </span>
                    </td>
                    <td className="px-6 py-3 text-slate-400">{item.confidence}</td>
                    <td className="px-6 py-3 font-mono text-[10px] text-slate-500">
                      {item.id ? item.id.slice(0, 12) : '—'}...
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
